package com.securevault.service;

import com.lowagie.text.*;
import com.lowagie.text.Font;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import com.securevault.dto.DashboardDtos.UserDashboard;
import com.securevault.entity.AuditLog;
import com.securevault.entity.Credential;
import com.securevault.repository.AuditLogRepository;
import lombok.RequiredArgsConstructor;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Service;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.List;

/** Reports &amp; Export module: password-health PDF and audit-log Excel exports. */
@Service
@RequiredArgsConstructor
public class ReportService {

    private final CredentialService credentialService;
    private final AnalyticsService analyticsService;
    private final AuditLogRepository auditRepo;

    private static final Color ACCENT = new Color(124, 58, 237);   // violet
    private static final Color INK = new Color(30, 27, 46);
    private static final DateTimeFormatter FMT =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm").withZone(ZoneId.systemDefault());

    /** Password-health & security summary as a styled PDF. */
    public byte[] passwordHealthPdf(Long userId, String username) {
        UserDashboard dash = analyticsService.userDashboard(userId);
        List<Credential> creds = credentialService.ownedEntities(userId);

        ByteArrayOutputStream out = new ByteArrayOutputStream();
        Document doc = new Document(PageSize.A4, 42, 42, 54, 42);
        PdfWriter.getInstance(doc, out);
        doc.open();

        Font h1 = new Font(Font.HELVETICA, 22, Font.BOLD, ACCENT);
        Font h2 = new Font(Font.HELVETICA, 13, Font.BOLD, INK);
        Font body = new Font(Font.HELVETICA, 10, Font.NORMAL, INK);
        Font small = new Font(Font.HELVETICA, 8, Font.NORMAL, Color.GRAY);

        doc.add(new Paragraph("SecureVault", h1));
        Paragraph sub = new Paragraph("Password Health & Security Report", h2);
        sub.setSpacingAfter(2);
        doc.add(sub);
        doc.add(new Paragraph("Account: " + username + "   •   Generated: " + FMT.format(java.time.Instant.now()), small));
        doc.add(Chunk.NEWLINE);

        // Summary metrics table
        PdfPTable summary = new PdfPTable(2);
        summary.setWidthPercentage(100);
        summary.setSpacingBefore(8);
        addMetric(summary, "Password Health Score", dash.passwordHealthScore() + " / 100", body, h2);
        addMetric(summary, "Total Credentials", String.valueOf(dash.totalCredentials()), body, h2);
        addMetric(summary, "Weak Passwords", String.valueOf(dash.weakPasswords()), body, h2);
        addMetric(summary, "Reused Passwords", String.valueOf(dash.reusedPasswords()), body, h2);
        addMetric(summary, "Expired Passwords", String.valueOf(dash.expiredPasswords()), body, h2);
        addMetric(summary, "Unresolved Alerts", String.valueOf(dash.unresolvedAlerts()), body, h2);
        doc.add(summary);

        doc.add(Chunk.NEWLINE);
        doc.add(new Paragraph("Credential Inventory", h2));

        PdfPTable table = new PdfPTable(new float[]{3, 2, 2, 1.4f});
        table.setWidthPercentage(100);
        table.setSpacingBefore(6);
        headerCell(table, "Title"); headerCell(table, "Type");
        headerCell(table, "Username"); headerCell(table, "Strength");
        for (Credential c : creds) {
            bodyCell(table, c.getTitle(), body);
            bodyCell(table, c.getType().name().replace('_', ' '), body);
            bodyCell(table, c.getUsername() == null ? "—" : c.getUsername(), body);
            bodyCell(table, c.getType().name().equals("SECURE_NOTE") ? "—" : c.getStrengthScore() + "%", body);
        }
        doc.add(table);

        doc.add(Chunk.NEWLINE);
        doc.add(new Paragraph("This report was generated by SecureVault. Secrets are never included in exports.", small));

        doc.close();
        return out.toByteArray();
    }

    /** Full audit trail as an Excel workbook. */
    public byte[] auditExcel(Long userId) {
        List<AuditLog> logs = auditRepo
                .findByUserIdOrderByCreatedAtDesc(userId, PageRequest.of(0, 1000))
                .getContent();

        try (Workbook wb = new XSSFWorkbook(); ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            Sheet sheet = wb.createSheet("Audit Log");

            CellStyle header = wb.createCellStyle();
            org.apache.poi.ss.usermodel.Font hf = wb.createFont();
            hf.setBold(true);
            hf.setColor(IndexedColors.WHITE.getIndex());
            header.setFont(hf);
            header.setFillForegroundColor(IndexedColors.INDIGO.getIndex());
            header.setFillPattern(FillPatternType.SOLID_FOREGROUND);

            String[] cols = {"Timestamp", "Action", "Category", "Detail", "IP Address"};
            org.apache.poi.ss.usermodel.Row headerRow = sheet.createRow(0);
            for (int i = 0; i < cols.length; i++) {
                org.apache.poi.ss.usermodel.Cell cell = headerRow.createCell(i);
                cell.setCellValue(cols[i]);
                cell.setCellStyle(header);
            }

            int r = 1;
            for (AuditLog log : logs) {
                org.apache.poi.ss.usermodel.Row row = sheet.createRow(r++);
                row.createCell(0).setCellValue(FMT.format(log.getCreatedAt()));
                row.createCell(1).setCellValue(nz(log.getAction()));
                row.createCell(2).setCellValue(nz(log.getCategory()));
                row.createCell(3).setCellValue(nz(log.getDetail()));
                row.createCell(4).setCellValue(nz(log.getIpAddress()));
            }
            for (int i = 0; i < cols.length; i++) sheet.autoSizeColumn(i);

            wb.write(out);
            return out.toByteArray();
        } catch (Exception e) {
            throw new IllegalStateException("Failed to build Excel report", e);
        }
    }

    // ---- pdf helpers ----

    private void addMetric(PdfPTable table, String label, String value, Font body, Font strong) {
        PdfPCell l = new PdfPCell(new Phrase(label, body));
        l.setBorderColor(new Color(230, 230, 240));
        l.setPadding(8);
        PdfPCell v = new PdfPCell(new Phrase(value, strong));
        v.setBorderColor(new Color(230, 230, 240));
        v.setHorizontalAlignment(Element.ALIGN_RIGHT);
        v.setPadding(8);
        table.addCell(l);
        table.addCell(v);
    }

    private void headerCell(PdfPTable table, String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text,
                new Font(Font.HELVETICA, 10, Font.BOLD, Color.WHITE)));
        cell.setBackgroundColor(ACCENT);
        cell.setPadding(6);
        table.addCell(cell);
    }

    private void bodyCell(PdfPTable table, String text, Font font) {
        PdfPCell cell = new PdfPCell(new Phrase(text, font));
        cell.setPadding(5);
        cell.setBorderColor(new Color(235, 235, 242));
        table.addCell(cell);
    }

    private String nz(String s) {
        return s == null ? "" : s;
    }
}
